name: CI MacOS

on:
  push:
    branches: [master, release, update]
  pull_request:
    branches: [master, release]

env:
  MACOSX_DEPLOYMENT_TARGET: 10.15

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Collect submodules
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
#          pip install -e git+https://github.com/dbouget/raidionics_seg_lib.git@master#egg=raidionicsseg

      - name: Built wheel for macos
        run: python setup.py bdist_wheel --plat-name macosx_10_15_x86_64

      - name: Upload Python wheel
        uses: actions/upload-artifact@v2
        with:
          name: Python wheel
          path: ${{github.workspace}}/dist/raidionicsrads-*.whl
          if-no-files-found: error

  test:
    needs: build
    runs-on: macos-11

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: "Python wheel"

      - name: Install wheel
        run: pip install --find-links=${{github.workspace}} raidionicsrads

      - name: Test CLI
        run: |
          raidionicsrads --help
          raidionicsseg --help

      - name: Clone repo
        uses: actions/checkout@v1

      - name: Segmentation pipeline unit test
        run: cd ${{github.workspace}}/tests && python segmentation_pipeline_test.py

      - name: Registration pipeline unit test
        run: cd ${{github.workspace}}/tests && python registration_pipeline_test.py